apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  namespace: nebula
  labels:
    app: portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      serviceAccountName: default
      containers:
      - name: portal
        image: ghcr.io/nebulaclouds/nebulaportal:v0.42.0
        command:
          - sleep
          - infinity
