apiVersion: v1
kind: Pod
metadata:
  name: portalpod
  namespace: nebula
spec:
  containers:
  - args:
    - sleep
    - infinity
    image: ghcr.io/nebulaclouds/nebulaportal:v0.42.0
    imagePullPolicy: Always
    name: portalcontainer
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 500m
        memory: 500Mi
    env:
    - name: HOST
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
  restartPolicy: Never
  serviceAccount: default
